"""
DataCenterOps — FastAPI Server
================================
Exposes the DataCenterOps environment over HTTP + WebSocket
using the official OpenEnv create_app() factory.

Endpoints (auto-generated by openenv-core):
    GET  /health           — liveness check
    GET  /schema           — action/observation schema
    POST /reset            — reset environment, returns initial observation
    POST /step             — step environment, returns observation + reward
    GET  /state            — full readable environment state
    WS   /ws               — persistent WebSocket session (preferred)
"""

import sys
import os
import uvicorn

# Add parent dir so server can import models.py and environment.py
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from openenv.core.env_server import create_app
from models import DataCenterAction, DataCenterObservation
from .datacenter_environment import DataCenterEnvironment

# Factory function: each WebSocket session gets its own env instance
def make_env() -> DataCenterEnvironment:
    return DataCenterEnvironment()

app = create_app(
    env=make_env,
    action_cls=DataCenterAction,
    observation_cls=DataCenterObservation,
    env_name="datacenter-ops-env",
)


def main() -> None:
    """Run the OpenEnv server."""
    uvicorn.run("server.app:app", host="0.0.0.0", port=7860, reload=False)


if __name__ == "__main__":
    main()
